/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE AIRLINK_AUTH_RESPONSE PACKING
package com.MAVLink.csAirLink;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Response to the authorization request
 */
public class msg_airlink_auth_response extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_AIRLINK_AUTH_RESPONSE = 52001;
    public static final int MAVLINK_MSG_LENGTH = 1;
    private static final long serialVersionUID = MAVLINK_MSG_ID_AIRLINK_AUTH_RESPONSE;

    
    /**
     * Response type
     */
    @Description("Response type")
    @Units("")
    public short resp_type;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_AIRLINK_AUTH_RESPONSE;

        packet.payload.putUnsignedByte(resp_type);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a airlink_auth_response message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.resp_type = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_airlink_auth_response() {
        this.msgid = MAVLINK_MSG_ID_AIRLINK_AUTH_RESPONSE;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_airlink_auth_response( short resp_type) {
        this.msgid = MAVLINK_MSG_ID_AIRLINK_AUTH_RESPONSE;

        this.resp_type = resp_type;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_airlink_auth_response( short resp_type, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_AIRLINK_AUTH_RESPONSE;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.resp_type = resp_type;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_airlink_auth_response(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_AIRLINK_AUTH_RESPONSE;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

      
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_AIRLINK_AUTH_RESPONSE - sysid:"+sysid+" compid:"+compid+" resp_type:"+resp_type+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_AIRLINK_AUTH_RESPONSE";
    }
}
        