/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Airspeed sensor flags
 */
public class AIRSPEED_SENSOR_FLAGS {
   public static final int AIRSPEED_SENSOR_UNHEALTHY = 0; /* Airspeed sensor is unhealthy | */
   public static final int AIRSPEED_SENSOR_USING = 1; /* True if the data from this sensor is being actively used by the flight controller for guidance, navigation or control. | */
   public static final int AIRSPEED_SENSOR_FLAGS_ENUM_END = 2; /*  | */
}