/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * 
 */
public class AVSS_HORSEFLY_OPERATION_MODE {
   public static final int MODE_HORSEFLY_MANUAL_CTRL = 0; /* In manual control mode | */
   public static final int MODE_HORSEFLY_AUTO_TAKEOFF = 1; /* In auto takeoff mode | */
   public static final int MODE_HORSEFLY_AUTO_LANDING = 2; /* In auto landing mode | */
   public static final int MODE_HORSEFLY_NAVI_GO_HOME = 3; /* In go home mode | */
   public static final int MODE_HORSEFLY_DROP = 4; /* In drop mode | */
   public static final int AVSS_HORSEFLY_OPERATION_MODE_ENUM_END = 5; /*  | */
}
            