/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Engine control options
 */
public class ENGINE_CONTROL_OPTIONS {
   public static final int ENGINE_CONTROL_OPTIONS_ALLOW_START_WHILE_DISARMED = 1; /* Allow starting the engine once while disarmed | */
   public static final int ENGINE_CONTROL_OPTIONS_ENUM_END = 2; /*  | */
}