/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Source for GLOBAL_POSITION measurement or estimate.
 */
public class GLOBAL_POSITION_SRC {
   public static final int GLOBAL_POSITION_SRC_UNKNOWN = 0; /* Source is unknown or not one of the listed types. | */
   public static final int GLOBAL_POSITION_SRC_GNSS = 1; /* Global Navigation Satellite System (e.g.: GPS, Galileo, Glonass, BeiDou). | */
   public static final int GLOBAL_POSITION_SRC_VISION = 2; /* Vision system (e.g.: map matching). | */
   public static final int GLOBAL_POSITION_SRC_PSEUDOLITES = 3; /* A pseudo-satellite system using transceiver beacons to perform GNSS-like positioning. | */
   public static final int GLOBAL_POSITION_SRC_TERRAIN = 4; /* Terrain referenced navigation. | */
   public static final int GLOBAL_POSITION_SRC_MAGNETIC = 5; /* Magnetic positioning. | */
   public static final int GLOBAL_POSITION_SRC_ESTIMATOR = 6; /* Estimated position based on various sensors (eg. a Kalman Filter). | */
   public static final int GLOBAL_POSITION_SRC_ENUM_END = 7; /*  | */
}