/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Reasons for denying an authorization request made with MAV_CMD_ARM_AUTHORIZATION_REQUEST. If the COMMAND_ACK result is MAV_RESULT_DENIED, this is used to set the reason in the result_param2 field.
 */
public class MAV_ARM_AUTH_DENIED_REASON {
   public static final int MAV_ARM_AUTH_DENIED_REASON_GENERIC = 0; /* Not a specific reason | */
   public static final int MAV_ARM_AUTH_DENIED_REASON_NONE = 1; /* Authorizer will send the error as string to GCS | */
   public static final int MAV_ARM_AUTH_DENIED_REASON_INVALID_WAYPOINT = 2; /* At least one waypoint have a invalid value | */
   public static final int MAV_ARM_AUTH_DENIED_REASON_TIMEOUT = 3; /* Timeout in the authorizer process(in case it depends on network) | */
   public static final int MAV_ARM_AUTH_DENIED_REASON_AIRSPACE_IN_USE = 4; /* Airspace of the mission in use by another vehicle, second result parameter can have the waypoint id that caused it to be denied. | */
   public static final int MAV_ARM_AUTH_DENIED_REASON_BAD_WEATHER = 5; /* Weather is not good to fly | */
   public static final int MAV_ARM_AUTH_DENIED_REASON_ENUM_END = 6; /*  | */
}