/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Parameter protocol error types (see PARAM_ERROR).
 */
public class MAV_PARAM_ERROR {
   public static final int MAV_PARAM_ERROR_NO_ERROR = 0; /* No error occurred (not expected in PARAM_ERROR but may be used in future implementations. | */
   public static final int MAV_PARAM_ERROR_DOES_NOT_EXIST = 1; /* Parameter does not exist | */
   public static final int MAV_PARAM_ERROR_VALUE_OUT_OF_RANGE = 2; /* Parameter value does not fit within accepted range | */
   public static final int MAV_PARAM_ERROR_PERMISSION_DENIED = 3; /* Caller is not permitted to set the value of this parameter | */
   public static final int MAV_PARAM_ERROR_COMPONENT_NOT_FOUND = 4; /* Unknown component specified | */
   public static final int MAV_PARAM_ERROR_READ_ONLY = 5; /* Parameter is read-only | */
   public static final int MAV_PARAM_ERROR_ENUM_END = 6; /*  | */
}