/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Gimbal manager capability flags.
 */
public class MAV_STORM32_GIMBAL_MANAGER_CAP_FLAGS {
   public static final int MAV_STORM32_GIMBAL_MANAGER_CAP_FLAGS_HAS_PROFILES = 1; /* The gimbal manager supports several profiles. | */
   public static final int MAV_STORM32_GIMBAL_MANAGER_CAP_FLAGS_ENUM_END = 2; /*  | */
}