/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * 
 */
public class NAV_VTOL_LAND_OPTIONS {
   public static final int NAV_VTOL_LAND_OPTIONS_DEFAULT = 0; /* Default autopilot landing behaviour. | */
   public static final int NAV_VTOL_LAND_OPTIONS_FW_SPIRAL_APPROACH = 1; /* Use a fixed wing spiral desent approach before landing. | */
   public static final int NAV_VTOL_LAND_OPTIONS_FW_APPROACH = 2; /* Use a fixed wing approach before detransitioning and landing vertically. | */
   public static final int NAV_VTOL_LAND_OPTIONS_ENUM_END = 3; /*  | */
}
            