/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * A mapping of plane flight modes for custom_mode field of heartbeat.
 */
public class PLANE_MODE {
   public static final int PLANE_MODE_MANUAL = 0; /* MANUAL | */
   public static final int PLANE_MODE_CIRCLE = 1; /* CIRCLE | */
   public static final int PLANE_MODE_STABILIZE = 2; /* STABILIZE | */
   public static final int PLANE_MODE_TRAINING = 3; /* TRAINING | */
   public static final int PLANE_MODE_ACRO = 4; /* ACRO | */
   public static final int PLANE_MODE_FLY_BY_WIRE_A = 5; /* FBWA | */
   public static final int PLANE_MODE_FLY_BY_WIRE_B = 6; /* FBWB | */
   public static final int PLANE_MODE_CRUISE = 7; /* CRUISE | */
   public static final int PLANE_MODE_AUTOTUNE = 8; /* AUTOTUNE | */
   public static final int PLANE_MODE_AUTO = 10; /* AUTO | */
   public static final int PLANE_MODE_RTL = 11; /* RTL | */
   public static final int PLANE_MODE_LOITER = 12; /* LOITER | */
   public static final int PLANE_MODE_TAKEOFF = 13; /* TAKEOFF | */
   public static final int PLANE_MODE_AVOID_ADSB = 14; /* AVOID ADSB | */
   public static final int PLANE_MODE_GUIDED = 15; /* GUIDED | */
   public static final int PLANE_MODE_INITIALIZING = 16; /* INITIALISING | */
   public static final int PLANE_MODE_QSTABILIZE = 17; /* QSTABILIZE | */
   public static final int PLANE_MODE_QHOVER = 18; /* QHOVER | */
   public static final int PLANE_MODE_QLOITER = 19; /* QLOITER | */
   public static final int PLANE_MODE_QLAND = 20; /* QLAND | */
   public static final int PLANE_MODE_QRTL = 21; /* QRTL | */
   public static final int PLANE_MODE_QAUTOTUNE = 22; /* QAUTOTUNE | */
   public static final int PLANE_MODE_QACRO = 23; /* QACRO | */
   public static final int PLANE_MODE_THERMAL = 24; /* THERMAL | */
   public static final int PLANE_MODE_LOITER_ALT_QLAND = 25; /* LOITER2QLAND | */
   public static final int PLANE_MODE_AUTOLAND = 26; /* AUTOLAND | */
   public static final int PLANE_MODE_ENUM_END = 27; /*  | */
}