/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Action for the accelerometer (param5) of MAV_CMD_PREFLIGHT_CALIBRATION.
 */
public class PREFLIGHT_CALIBRATION_ACCELEROMETER {
   public static final int PREFLIGHT_CALIBRATION_ACCELEROMETER_NONE = 0; /* No action. | */
   public static final int PREFLIGHT_CALIBRATION_ACCELEROMETER_FULL = 1; /* Full 6-position accelerometer calibration. | */
   public static final int PREFLIGHT_CALIBRATION_ACCELEROMETER_TRIM = 2; /* Board level (trim) calibration. | */
   public static final int PREFLIGHT_CALIBRATION_ACCELEROMETER_TEMPERATURE = 3; /* Accelerometer temperature calibration. | */
   public static final int PREFLIGHT_CALIBRATION_ACCELEROMETER_SIMPLE = 4; /* Simple accelerometer calibration. | */
   public static final int PREFLIGHT_CALIBRATION_ACCELEROMETER_FORCE_SAVE = 76; /* Force-accept the existing accelerometer calibration as valid without re-running it. Useful after a parameter reload that cleared calibration validity flags. | */
   public static final int PREFLIGHT_CALIBRATION_ACCELEROMETER_ENUM_END = 77; /*  | */
}