/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Action for the magnetometer (param2) of MAV_CMD_PREFLIGHT_CALIBRATION.
 */
public class PREFLIGHT_CALIBRATION_MAGNETOMETER {
   public static final int PREFLIGHT_CALIBRATION_MAGNETOMETER_NONE = 0; /* No action. | */
   public static final int PREFLIGHT_CALIBRATION_MAGNETOMETER_START = 1; /* Start magnetometer calibration. | */
   public static final int PREFLIGHT_CALIBRATION_MAGNETOMETER_FORCE_SAVE = 76; /* Force-accept the existing compass calibration as valid without re-running it. Useful after a parameter reload that cleared calibration validity flags. | */
   public static final int PREFLIGHT_CALIBRATION_MAGNETOMETER_ENUM_END = 77; /*  | */
}