/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * RC sub-type of types defined in RC_TYPE. Used in MAV_CMD_START_RX_PAIR. Ignored if value does not correspond to the set RC_TYPE.
 */
public class RC_SUB_TYPE {
   public static final int RC_SUB_TYPE_SPEKTRUM_DSM2 = 0; /* Spektrum DSM2 | */
   public static final int RC_SUB_TYPE_SPEKTRUM_DSMX = 1; /* Spektrum DSMX | */
   public static final int RC_SUB_TYPE_SPEKTRUM_DSMX8 = 2; /* Spektrum DSMX8 | */
   public static final int RC_SUB_TYPE_ENUM_END = 3; /*  | */
}