/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Video stream encodings
 */
public class VIDEO_STREAM_ENCODING {
   public static final int VIDEO_STREAM_ENCODING_UNKNOWN = 0; /* Stream encoding is unknown | */
   public static final int VIDEO_STREAM_ENCODING_H264 = 1; /* Stream encoding is H.264 | */
   public static final int VIDEO_STREAM_ENCODING_H265 = 2; /* Stream encoding is H.265 | */
   public static final int VIDEO_STREAM_ENCODING_ENUM_END = 3; /*  | */
}