/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Stream status flags (Bitmap)
 */
public class VIDEO_STREAM_STATUS_FLAGS {
   public static final int VIDEO_STREAM_STATUS_FLAGS_RUNNING = 1; /* Stream is active (running) | */
   public static final int VIDEO_STREAM_STATUS_FLAGS_THERMAL = 2; /* Stream is thermal imaging | */
   public static final int VIDEO_STREAM_STATUS_FLAGS_THERMAL_RANGE_ENABLED = 4; /* Stream can report absolute thermal range (see CAMERA_THERMAL_RANGE). | */
   public static final int VIDEO_STREAM_STATUS_FLAGS_ENUM_END = 5; /*  | */
}