/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE ARRAY_TEST_0 PACKING
package com.MAVLink.python_array_test;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Array test #0.
 */
public class msg_array_test_0 extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_ARRAY_TEST_0 = 17150;
    public static final int MAVLINK_MSG_LENGTH = 33;
    private static final long serialVersionUID = MAVLINK_MSG_ID_ARRAY_TEST_0;

    
    /**
     * Value array
     */
    @Description("Value array")
    @Units("")
    public long ar_u32[] = new long[4];
    
    /**
     * Value array
     */
    @Description("Value array")
    @Units("")
    public int ar_u16[] = new int[4];
    
    /**
     * Stub field
     */
    @Description("Stub field")
    @Units("")
    public short v1;
    
    /**
     * Value array
     */
    @Description("Value array")
    @Units("")
    public byte ar_i8[] = new byte[4];
    
    /**
     * Value array
     */
    @Description("Value array")
    @Units("")
    public short ar_u8[] = new short[4];
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_ARRAY_TEST_0;

        
        for (int i = 0; i < ar_u32.length; i++) {
            packet.payload.putUnsignedInt(ar_u32[i]);
        }
                    
        
        for (int i = 0; i < ar_u16.length; i++) {
            packet.payload.putUnsignedShort(ar_u16[i]);
        }
                    
        packet.payload.putUnsignedByte(v1);
        
        for (int i = 0; i < ar_i8.length; i++) {
            packet.payload.putByte(ar_i8[i]);
        }
                    
        
        for (int i = 0; i < ar_u8.length; i++) {
            packet.payload.putUnsignedByte(ar_u8[i]);
        }
                    
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a array_test_0 message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        
        for (int i = 0; i < this.ar_u32.length; i++) {
            this.ar_u32[i] = payload.getUnsignedInt();
        }
                
        
        for (int i = 0; i < this.ar_u16.length; i++) {
            this.ar_u16[i] = payload.getUnsignedShort();
        }
                
        this.v1 = payload.getUnsignedByte();
        
        for (int i = 0; i < this.ar_i8.length; i++) {
            this.ar_i8[i] = payload.getByte();
        }
                
        
        for (int i = 0; i < this.ar_u8.length; i++) {
            this.ar_u8[i] = payload.getUnsignedByte();
        }
                
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_array_test_0() {
        this.msgid = MAVLINK_MSG_ID_ARRAY_TEST_0;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_array_test_0( long[] ar_u32, int[] ar_u16, short v1, byte[] ar_i8, short[] ar_u8) {
        this.msgid = MAVLINK_MSG_ID_ARRAY_TEST_0;

        this.ar_u32 = ar_u32;
        this.ar_u16 = ar_u16;
        this.v1 = v1;
        this.ar_i8 = ar_i8;
        this.ar_u8 = ar_u8;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_array_test_0( long[] ar_u32, int[] ar_u16, short v1, byte[] ar_i8, short[] ar_u8, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_ARRAY_TEST_0;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.ar_u32 = ar_u32;
        this.ar_u16 = ar_u16;
        this.v1 = v1;
        this.ar_i8 = ar_i8;
        this.ar_u8 = ar_u8;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_array_test_0(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_ARRAY_TEST_0;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

              
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_ARRAY_TEST_0 - sysid:"+sysid+" compid:"+compid+" ar_u32:"+ar_u32+" ar_u16:"+ar_u16+" v1:"+v1+" ar_i8:"+ar_i8+" ar_u8:"+ar_u8+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_ARRAY_TEST_0";
    }
}
        