/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE TIMESYNC PACKING
package com.mavlink.common;
import com.mavlink.MAVLinkPacket;
import com.mavlink.messages.MAVLinkMessage;
import com.mavlink.messages.MAVLinkPayload;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

        
/**
 * Time synchronization message.
 */
public class msg_timesync extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_TIMESYNC = 111;
    public static final int MAVLINK_MSG_LENGTH = 16;
    private static final long serialVersionUID = MAVLINK_MSG_ID_TIMESYNC;

      
    /**
     * Time sync timestamp 1
     */
    public long tc1;
      
    /**
     * Time sync timestamp 2
     */
    public long ts1;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_TIMESYNC;
        
        packet.payload.putLong(tc1);
        packet.payload.putLong(ts1);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a timesync message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.tc1 = payload.getLong();
        this.ts1 = payload.getLong();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_timesync() {
        this.msgid = MAVLINK_MSG_ID_TIMESYNC;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_timesync( long tc1, long ts1) {
        this.msgid = MAVLINK_MSG_ID_TIMESYNC;

        this.tc1 = tc1;
        this.ts1 = ts1;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_timesync( long tc1, long ts1, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_TIMESYNC;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.tc1 = tc1;
        this.ts1 = ts1;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_timesync(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_TIMESYNC;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from JSON Object
     */
    public msg_timesync(JSONObject jo) {
        this.msgid = MAVLINK_MSG_ID_TIMESYNC;

        readJSONheader(jo);
        
         
        if (jo.has("tc1")) {
            final JSONArray ja_tc1 = jo.optJSONArray("tc1");
            if (ja_tc1 == null) {
                this.tc1 = jo.optLong("tc1", 0);
            } else if (ja_tc1.length() > 0) {
                this.tc1 = ja_tc1.optLong(0, 0);
            }
        }
                    
         
        if (jo.has("ts1")) {
            final JSONArray ja_ts1 = jo.optJSONArray("ts1");
            if (ja_ts1 == null) {
                this.ts1 = jo.optLong("ts1", 0);
            } else if (ja_ts1.length() > 0) {
                this.ts1 = ja_ts1.optLong(0, 0);
            }
        }
                    
        
        
    }
    
    /**
     * Convert this class to a JSON Object
     */
    @Override
    public JSONObject toJSON() throws JSONException {
        final JSONObject jo = getJSONheader();
        
        jo.put("tc1", tc1);
        jo.put("ts1", ts1);
        
        
        return jo;
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_TIMESYNC - sysid:"+sysid+" compid:"+compid+" tc1:"+tc1+" ts1:"+ts1+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_TIMESYNC";
    }
}
        