/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE GLOBAL_POSITION_SENSOR PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Reports measurement/estimate from a global position sensor. Used as navigation fusion source and optionally displayed in the UI.
 */
public class msg_global_position_sensor extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_GLOBAL_POSITION_SENSOR = 296;
    public static final int MAVLINK_MSG_LENGTH = 41;
    private static final long serialVersionUID = MAVLINK_MSG_ID_GLOBAL_POSITION_SENSOR;

    
    /**
     * Timestamp of message transmission (UNIX Epoch time or time since system boot). The receiving end can infer timestamp format (since 1.1.1970 or since system boot) by checking for the magnitude of the number.
     */
    @Description("Timestamp of message transmission (UNIX Epoch time or time since system boot). The receiving end can infer timestamp format (since 1.1.1970 or since system boot) by checking for the magnitude of the number.")
    @Units("us")
    public long time_usec;
    
    /**
     * The time spent in processing the sensor data that is the basis for this position. The recipient can use this to improve time alignment of the data. This is the time between measurement (e.g. camera exposure time) and transmission of this message. Set to NaN if not known.
     */
    @Description("The time spent in processing the sensor data that is the basis for this position. The recipient can use this to improve time alignment of the data. This is the time between measurement (e.g. camera exposure time) and transmission of this message. Set to NaN if not known.")
    @Units("us")
    public long processing_time;
    
    /**
     * Latitude (WGS84)
     */
    @Description("Latitude (WGS84)")
    @Units("degE7")
    public int lat;
    
    /**
     * Longitude (WGS84)
     */
    @Description("Longitude (WGS84)")
    @Units("degE7")
    public int lon;
    
    /**
     * Altitude (WGS84 elipsoid), preferred if available
     */
    @Description("Altitude (WGS84 elipsoid), preferred if available")
    @Units("m")
    public float alt_ellipsoid;
    
    /**
     * Altitude (MSL - position-system specific value) use if no alt_ellipsoid available
     */
    @Description("Altitude (MSL - position-system specific value) use if no alt_ellipsoid available")
    @Units("m")
    public float alt;
    
    /**
     * Standard deviation of horizontal position error
     */
    @Description("Standard deviation of horizontal position error")
    @Units("m")
    public float eph;
    
    /**
     * Standard deviation of vertical position error
     */
    @Description("Standard deviation of vertical position error")
    @Units("m")
    public float epv;
    
    /**
     * System ID (ID of target system, normally autopilot and ground station).
     */
    @Description("System ID (ID of target system, normally autopilot and ground station).")
    @Units("")
    public short target_system;
    
    /**
     * Component ID (normally 0 for broadcast).
     */
    @Description("Component ID (normally 0 for broadcast).")
    @Units("")
    public short target_component;
    
    /**
     * Sensor ID
     */
    @Description("Sensor ID")
    @Units("")
    public short id;
    
    /**
     * Source of position/estimate (such as GNSS, estimator, etc.)
     */
    @Description("Source of position/estimate (such as GNSS, estimator, etc.)")
    @Units("")
    public short source;
    
    /**
     * Status flags
     */
    @Description("Status flags")
    @Units("")
    public short flags;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_GLOBAL_POSITION_SENSOR;

        packet.payload.putUnsignedLong(time_usec);
        packet.payload.putUnsignedInt(processing_time);
        packet.payload.putInt(lat);
        packet.payload.putInt(lon);
        packet.payload.putFloat(alt_ellipsoid);
        packet.payload.putFloat(alt);
        packet.payload.putFloat(eph);
        packet.payload.putFloat(epv);
        packet.payload.putUnsignedByte(target_system);
        packet.payload.putUnsignedByte(target_component);
        packet.payload.putUnsignedByte(id);
        packet.payload.putUnsignedByte(source);
        packet.payload.putUnsignedByte(flags);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a global_position_sensor message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.time_usec = payload.getUnsignedLong();
        this.processing_time = payload.getUnsignedInt();
        this.lat = payload.getInt();
        this.lon = payload.getInt();
        this.alt_ellipsoid = payload.getFloat();
        this.alt = payload.getFloat();
        this.eph = payload.getFloat();
        this.epv = payload.getFloat();
        this.target_system = payload.getUnsignedByte();
        this.target_component = payload.getUnsignedByte();
        this.id = payload.getUnsignedByte();
        this.source = payload.getUnsignedByte();
        this.flags = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_global_position_sensor() {
        this.msgid = MAVLINK_MSG_ID_GLOBAL_POSITION_SENSOR;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_global_position_sensor( long time_usec, long processing_time, int lat, int lon, float alt_ellipsoid, float alt, float eph, float epv, short target_system, short target_component, short id, short source, short flags) {
        this.msgid = MAVLINK_MSG_ID_GLOBAL_POSITION_SENSOR;

        this.time_usec = time_usec;
        this.processing_time = processing_time;
        this.lat = lat;
        this.lon = lon;
        this.alt_ellipsoid = alt_ellipsoid;
        this.alt = alt;
        this.eph = eph;
        this.epv = epv;
        this.target_system = target_system;
        this.target_component = target_component;
        this.id = id;
        this.source = source;
        this.flags = flags;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_global_position_sensor( long time_usec, long processing_time, int lat, int lon, float alt_ellipsoid, float alt, float eph, float epv, short target_system, short target_component, short id, short source, short flags, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_GLOBAL_POSITION_SENSOR;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.time_usec = time_usec;
        this.processing_time = processing_time;
        this.lat = lat;
        this.lon = lon;
        this.alt_ellipsoid = alt_ellipsoid;
        this.alt = alt;
        this.eph = eph;
        this.epv = epv;
        this.target_system = target_system;
        this.target_component = target_component;
        this.id = id;
        this.source = source;
        this.flags = flags;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_global_position_sensor(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_GLOBAL_POSITION_SENSOR;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                              
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_GLOBAL_POSITION_SENSOR - sysid:"+sysid+" compid:"+compid+" time_usec:"+time_usec+" processing_time:"+processing_time+" lat:"+lat+" lon:"+lon+" alt_ellipsoid:"+alt_ellipsoid+" alt:"+alt+" eph:"+eph+" epv:"+epv+" target_system:"+target_system+" target_component:"+target_component+" id:"+id+" source:"+source+" flags:"+flags+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_GLOBAL_POSITION_SENSOR";
    }
}
        