/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE FILE_TRANSFER_PROTOCOL PACKING
package com.mavlink.common;
import com.mavlink.MAVLinkPacket;
import com.mavlink.messages.MAVLinkMessage;
import com.mavlink.messages.MAVLinkPayload;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

        
/**
 * File transfer message
 */
public class msg_file_transfer_protocol extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL = 110;
    public static final int MAVLINK_MSG_LENGTH = 254;
    private static final long serialVersionUID = MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL;

      
    /**
     * Network ID (0 for broadcast)
     */
    public short target_network;
      
    /**
     * System ID (0 for broadcast)
     */
    public short target_system;
      
    /**
     * Component ID (0 for broadcast)
     */
    public short target_component;
      
    /**
     * Variable length payload. The length is defined by the remaining message length when subtracting the header and other fields.  The entire content of this block is opaque unless you understand any the encoding message_type.  The particular encoding used can be extension specific and might not always be documented as part of the mavlink specification.
     */
    public short[] payload = new short[251];
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL;
        
        packet.payload.putUnsignedByte(target_network);
        packet.payload.putUnsignedByte(target_system);
        packet.payload.putUnsignedByte(target_component);
        
        for (int i = 0; i < payload.length; i++) {
            packet.payload.putUnsignedByte(payload[i]);
        }
                    
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a file_transfer_protocol message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.target_network = payload.getUnsignedByte();
        this.target_system = payload.getUnsignedByte();
        this.target_component = payload.getUnsignedByte();
         
        for (int i = 0; i < this.payload.length; i++) {
            this.payload[i] = payload.getUnsignedByte();
        }
                
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_file_transfer_protocol() {
        this.msgid = MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_file_transfer_protocol( short target_network, short target_system, short target_component, short[] payload) {
        this.msgid = MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL;

        this.target_network = target_network;
        this.target_system = target_system;
        this.target_component = target_component;
        this.payload = payload;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_file_transfer_protocol( short target_network, short target_system, short target_component, short[] payload, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.target_network = target_network;
        this.target_system = target_system;
        this.target_component = target_component;
        this.payload = payload;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_file_transfer_protocol(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from JSON Object
     */
    public msg_file_transfer_protocol(JSONObject jo) {
        this.msgid = MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL;

        readJSONheader(jo);
        
        this.target_network = (short)jo.optInt("target_network",0);
        this.target_system = (short)jo.optInt("target_system",0);
        this.target_component = (short)jo.optInt("target_component",0);
         
        if (jo.has("payload")) {
            JSONArray ja_payload = jo.optJSONArray("payload");
            if (ja_payload == null) {
                this.payload[0] = (short)jo.optInt("payload", 0);
            } else {
                for (int i = 0; i < Math.min(this.payload.length, ja_payload.length()); i++) {
                    this.payload[i] = (short)ja_payload.optInt(i,0);
                }
            }
        }
                    
        
        
    }
    
    /**
     * Convert this class to a JSON Object
     */
    @Override
    public JSONObject toJSON() throws JSONException {
        final JSONObject jo = getJSONheader();
        
        jo.put("target_network", target_network);
        jo.put("target_system", target_system);
        jo.put("target_component", target_component);
         
        JSONArray ja_payload = new JSONArray();
        for (int i = 0; i < this.payload.length; i++) {
            ja_payload.put(this.payload[i]);
        }
        jo.putOpt("payload", ja_payload);
                
        
        
        return jo;
    }

            
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL - sysid:"+sysid+" compid:"+compid+" target_network:"+target_network+" target_system:"+target_system+" target_component:"+target_component+" payload:"+payload+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_FILE_TRANSFER_PROTOCOL";
    }
}
        