apply plugin: 'com.android.library'

android {
    compileSdkVersion android_build_sdk_version
    buildToolsVersion android_build_tools_version
    defaultConfig {
        minSdkVersion android_build_min_sdk_version
        targetSdkVersion android_build_target_sdk_version
        multiDexEnabled true
    }
    // Jai - update for gradle 8.x
    buildFeatures {
        buildConfig = true
    }
    namespace 'ap.andruavmiddlelibrary'
    // Jai - update for gradle 8.x
    buildTypes {
        release {
            buildConfigField "boolean", "IS_DEBUG", "false"
            minifyEnabled false
        }
        debug {
            buildConfigField "boolean", "IS_DEBUG", "true"
            minifyEnabled false
        }
    }



    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }
}


dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    testImplementation 'junit:junit:4.12'
    api project(':andruavProtocol')
    api project(':webrtc')
    api 'org.greenrobot:greendao:3.3.0'
    api 'com.squareup.okhttp3:okhttp:3.14.9'
    //api 'org.webrtc:google-webrtc:1.0.30039'
    api 'org.greenrobot:eventbus:3.3.1'
}

