apply plugin: 'com.android.application'



android {

    compileSdkVersion android_build_sdk_version
    buildToolsVersion android_build_tools_version

    defaultConfig {
        applicationId 'arudpilot.andruav'
        minSdkVersion android_build_min_sdk_version
        targetSdkVersion android_build_target_sdk_version
        versionName '11.6.0'
        versionCode 1110600
        multiDexEnabled true
    }

    // Jai - update for gradle 8.x
    buildFeatures {
        buildConfig = true
    }
    namespace 'ap.andruav_ap'
    // Jai - update for gradle 8.x


    buildTypes {

        debug {
            debuggable true
            minifyEnabled false
            android.applicationVariants.all { variant ->
                variant.outputs.all {
                    outputFileName = "Andruav_debug_" + variant.properties.get('flavorName') + "." + defaultConfig.versionName + "." + releaseTime() + ".apk"
                }
            }
        }

        release {
            logger.info('Release Built')
            debuggable false
            minifyEnabled false
            signingConfig signingConfigs.debug
            android.applicationVariants.all { variant ->
                variant.outputs.all {
                    outputFileName = "Andruav_release_" + variant.properties.get('flavorName') + "." + defaultConfig.versionName + "." + releaseTime() + ".apk"
                }
            }
        }




    }






    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

// Remove libraries that conflict with libraries already included with Android
configurations {
    all*.exclude group: "xmlpull", module: "xmlpull"
    all*.exclude group: "org.apache.commons", module: "commons-compress"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

dependencies {
    implementation project(':andruavmiddlelibrary')
    implementation project(':ClientLib')
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.multidex:multidex:2.0.1'
    testImplementation 'junit:junit:4.12'
    implementation 'com.androidplot:androidplot-core:1.5.11'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
    implementation project(':rangebar-release')
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.preference:preference:1.2.1'
}

