/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE AVSS_PRS_SYS_STATUS PACKING
package com.MAVLink.AVSSUAS;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 *  AVSS PRS system status.
 */
public class msg_avss_prs_sys_status extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS = 60050;
    public static final int MAVLINK_MSG_LENGTH = 14;
    private static final long serialVersionUID = MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS;

    
    /**
     * Timestamp (time since PRS boot).
     */
    @Description("Timestamp (time since PRS boot).")
    @Units("ms")
    public long time_boot_ms;
    
    /**
     * PRS error statuses
     */
    @Description("PRS error statuses")
    @Units("")
    public long error_status;
    
    /**
     * Estimated battery run-time without a remote connection and PRS battery voltage
     */
    @Description("Estimated battery run-time without a remote connection and PRS battery voltage")
    @Units("")
    public long battery_status;
    
    /**
     * PRS arm statuses
     */
    @Description("PRS arm statuses")
    @Units("")
    public short arm_status;
    
    /**
     * PRS battery charge statuses
     */
    @Description("PRS battery charge statuses")
    @Units("")
    public short charge_status;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS;

        packet.payload.putUnsignedInt(time_boot_ms);
        packet.payload.putUnsignedInt(error_status);
        packet.payload.putUnsignedInt(battery_status);
        packet.payload.putUnsignedByte(arm_status);
        packet.payload.putUnsignedByte(charge_status);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a avss_prs_sys_status message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.time_boot_ms = payload.getUnsignedInt();
        this.error_status = payload.getUnsignedInt();
        this.battery_status = payload.getUnsignedInt();
        this.arm_status = payload.getUnsignedByte();
        this.charge_status = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_avss_prs_sys_status() {
        this.msgid = MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_avss_prs_sys_status( long time_boot_ms, long error_status, long battery_status, short arm_status, short charge_status) {
        this.msgid = MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS;

        this.time_boot_ms = time_boot_ms;
        this.error_status = error_status;
        this.battery_status = battery_status;
        this.arm_status = arm_status;
        this.charge_status = charge_status;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_avss_prs_sys_status( long time_boot_ms, long error_status, long battery_status, short arm_status, short charge_status, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.time_boot_ms = time_boot_ms;
        this.error_status = error_status;
        this.battery_status = battery_status;
        this.arm_status = arm_status;
        this.charge_status = charge_status;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_avss_prs_sys_status(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

              
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS - sysid:"+sysid+" compid:"+compid+" time_boot_ms:"+time_boot_ms+" error_status:"+error_status+" battery_status:"+battery_status+" arm_status:"+arm_status+" charge_status:"+charge_status+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_AVSS_PRS_SYS_STATUS";
    }
}
        