/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE MLRS_RADIO_LINK_INFORMATION PACKING
package com.MAVLink.storm32;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Radio link information. Tx: ground-side device, Rx: vehicle-side device.
        The values of the fields in this message do normally not or only slowly change with time, and for most times the message can be send at a low rate, like 0.2 Hz.
        If values change then the message should temporarily be send more often to inform the system about the changes.
        The target_system field should normally be set to the system id of the system the link is connected to, typically the flight controller.
        The target_component field can normally be set to 0, so that all components of the system can receive the message.
      
 */
public class msg_mlrs_radio_link_information extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_MLRS_RADIO_LINK_INFORMATION = 60046;
    public static final int MAVLINK_MSG_LENGTH = 28;
    private static final long serialVersionUID = MAVLINK_MSG_ID_MLRS_RADIO_LINK_INFORMATION;

    
    /**
     * Frame rate in Hz (frames per second) for Tx to Rx transmission. 0: unknown.
     */
    @Description("Frame rate in Hz (frames per second) for Tx to Rx transmission. 0: unknown.")
    @Units("Hz")
    public int tx_frame_rate;
    
    /**
     * Frame rate in Hz (frames per second) for Rx to Tx transmission. Normally equal to tx_packet_rate. 0: unknown.
     */
    @Description("Frame rate in Hz (frames per second) for Rx to Tx transmission. Normally equal to tx_packet_rate. 0: unknown.")
    @Units("Hz")
    public int rx_frame_rate;
    
    /**
     * Maximum data rate of serial stream in bytes/s for Tx to Rx transmission. 0: unknown. UINT16_MAX: data rate is 64 KBytes/s or larger.
     */
    @Description("Maximum data rate of serial stream in bytes/s for Tx to Rx transmission. 0: unknown. UINT16_MAX: data rate is 64 KBytes/s or larger.")
    @Units("")
    public int tx_ser_data_rate;
    
    /**
     * Maximum data rate of serial stream in bytes/s for Rx to Tx transmission. 0: unknown. UINT16_MAX: data rate is 64 KBytes/s or larger.
     */
    @Description("Maximum data rate of serial stream in bytes/s for Rx to Tx transmission. 0: unknown. UINT16_MAX: data rate is 64 KBytes/s or larger.")
    @Units("")
    public int rx_ser_data_rate;
    
    /**
     * System ID (ID of target system, normally flight controller).
     */
    @Description("System ID (ID of target system, normally flight controller).")
    @Units("")
    public short target_system;
    
    /**
     * Component ID (normally 0 for broadcast).
     */
    @Description("Component ID (normally 0 for broadcast).")
    @Units("")
    public short target_component;
    
    /**
     * Radio link type. 0: unknown/generic type.
     */
    @Description("Radio link type. 0: unknown/generic type.")
    @Units("")
    public short type;
    
    /**
     * Operation mode. Radio link dependent. UINT8_MAX: ignore/unknown.
     */
    @Description("Operation mode. Radio link dependent. UINT8_MAX: ignore/unknown.")
    @Units("")
    public short mode;
    
    /**
     * Tx transmit power in dBm. INT8_MAX: unknown.
     */
    @Description("Tx transmit power in dBm. INT8_MAX: unknown.")
    @Units("dBm")
    public byte tx_power;
    
    /**
     * Rx transmit power in dBm. INT8_MAX: unknown.
     */
    @Description("Rx transmit power in dBm. INT8_MAX: unknown.")
    @Units("dBm")
    public byte rx_power;
    
    /**
     * Operation mode as human readable string. Radio link dependent. Terminated by NULL if the string length is less than 6 chars and WITHOUT NULL termination if the length is exactly 6 chars - applications have to provide 6+1 bytes storage if the mode is stored as string. Use a zero-length string if not known.
     */
    @Description("Operation mode as human readable string. Radio link dependent. Terminated by NULL if the string length is less than 6 chars and WITHOUT NULL termination if the length is exactly 6 chars - applications have to provide 6+1 bytes storage if the mode is stored as string. Use a zero-length string if not known.")
    @Units("")
    public byte mode_str[] = new byte[6];
    
    /**
     * Frequency band as human readable string. Radio link dependent. Terminated by NULL if the string length is less than 6 chars and WITHOUT NULL termination if the length is exactly 6 chars - applications have to provide 6+1 bytes storage if the mode is stored as string. Use a zero-length string if not known.
     */
    @Description("Frequency band as human readable string. Radio link dependent. Terminated by NULL if the string length is less than 6 chars and WITHOUT NULL termination if the length is exactly 6 chars - applications have to provide 6+1 bytes storage if the mode is stored as string. Use a zero-length string if not known.")
    @Units("")
    public byte band_str[] = new byte[6];
    
    /**
     * Receive sensitivity of Tx in inverted dBm. 1..255 represents -1..-255 dBm, 0: unknown.
     */
    @Description("Receive sensitivity of Tx in inverted dBm. 1..255 represents -1..-255 dBm, 0: unknown.")
    @Units("")
    public short tx_receive_sensitivity;
    
    /**
     * Receive sensitivity of Rx in inverted dBm. 1..255 represents -1..-255 dBm, 0: unknown.
     */
    @Description("Receive sensitivity of Rx in inverted dBm. 1..255 represents -1..-255 dBm, 0: unknown.")
    @Units("")
    public short rx_receive_sensitivity;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_MLRS_RADIO_LINK_INFORMATION;

        packet.payload.putUnsignedShort(tx_frame_rate);
        packet.payload.putUnsignedShort(rx_frame_rate);
        packet.payload.putUnsignedShort(tx_ser_data_rate);
        packet.payload.putUnsignedShort(rx_ser_data_rate);
        packet.payload.putUnsignedByte(target_system);
        packet.payload.putUnsignedByte(target_component);
        packet.payload.putUnsignedByte(type);
        packet.payload.putUnsignedByte(mode);
        packet.payload.putByte(tx_power);
        packet.payload.putByte(rx_power);
        
        for (int i = 0; i < mode_str.length; i++) {
            packet.payload.putByte(mode_str[i]);
        }
                    
        
        for (int i = 0; i < band_str.length; i++) {
            packet.payload.putByte(band_str[i]);
        }
                    
        packet.payload.putUnsignedByte(tx_receive_sensitivity);
        packet.payload.putUnsignedByte(rx_receive_sensitivity);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a mlrs_radio_link_information message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.tx_frame_rate = payload.getUnsignedShort();
        this.rx_frame_rate = payload.getUnsignedShort();
        this.tx_ser_data_rate = payload.getUnsignedShort();
        this.rx_ser_data_rate = payload.getUnsignedShort();
        this.target_system = payload.getUnsignedByte();
        this.target_component = payload.getUnsignedByte();
        this.type = payload.getUnsignedByte();
        this.mode = payload.getUnsignedByte();
        this.tx_power = payload.getByte();
        this.rx_power = payload.getByte();
        
        for (int i = 0; i < this.mode_str.length; i++) {
            this.mode_str[i] = payload.getByte();
        }
                
        
        for (int i = 0; i < this.band_str.length; i++) {
            this.band_str[i] = payload.getByte();
        }
                
        this.tx_receive_sensitivity = payload.getUnsignedByte();
        this.rx_receive_sensitivity = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_mlrs_radio_link_information() {
        this.msgid = MAVLINK_MSG_ID_MLRS_RADIO_LINK_INFORMATION;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_mlrs_radio_link_information( int tx_frame_rate, int rx_frame_rate, int tx_ser_data_rate, int rx_ser_data_rate, short target_system, short target_component, short type, short mode, byte tx_power, byte rx_power, byte[] mode_str, byte[] band_str, short tx_receive_sensitivity, short rx_receive_sensitivity) {
        this.msgid = MAVLINK_MSG_ID_MLRS_RADIO_LINK_INFORMATION;

        this.tx_frame_rate = tx_frame_rate;
        this.rx_frame_rate = rx_frame_rate;
        this.tx_ser_data_rate = tx_ser_data_rate;
        this.rx_ser_data_rate = rx_ser_data_rate;
        this.target_system = target_system;
        this.target_component = target_component;
        this.type = type;
        this.mode = mode;
        this.tx_power = tx_power;
        this.rx_power = rx_power;
        this.mode_str = mode_str;
        this.band_str = band_str;
        this.tx_receive_sensitivity = tx_receive_sensitivity;
        this.rx_receive_sensitivity = rx_receive_sensitivity;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_mlrs_radio_link_information( int tx_frame_rate, int rx_frame_rate, int tx_ser_data_rate, int rx_ser_data_rate, short target_system, short target_component, short type, short mode, byte tx_power, byte rx_power, byte[] mode_str, byte[] band_str, short tx_receive_sensitivity, short rx_receive_sensitivity, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_MLRS_RADIO_LINK_INFORMATION;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.tx_frame_rate = tx_frame_rate;
        this.rx_frame_rate = rx_frame_rate;
        this.tx_ser_data_rate = tx_ser_data_rate;
        this.rx_ser_data_rate = rx_ser_data_rate;
        this.target_system = target_system;
        this.target_component = target_component;
        this.type = type;
        this.mode = mode;
        this.tx_power = tx_power;
        this.rx_power = rx_power;
        this.mode_str = mode_str;
        this.band_str = band_str;
        this.tx_receive_sensitivity = tx_receive_sensitivity;
        this.rx_receive_sensitivity = rx_receive_sensitivity;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_mlrs_radio_link_information(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_MLRS_RADIO_LINK_INFORMATION;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                         
    /**
    * Sets the buffer of this message with a string, adds the necessary padding
    */
    public void setMode_Str(String str) {
        int len = Math.min(str.length(), 6);
        for (int i=0; i<len; i++) {
            mode_str[i] = (byte) str.charAt(i);
        }

        for (int i=len; i<6; i++) {            // padding for the rest of the buffer
            mode_str[i] = 0;
        }
    }

    /**
    * Gets the message, formatted as a string
    */
    public String getMode_Str() {
        StringBuffer buf = new StringBuffer();
        for (int i = 0; i < 6; i++) {
            if (mode_str[i] != 0)
                buf.append((char) mode_str[i]);
            else
                break;
        }
        return buf.toString();

    }
                          
    /**
    * Sets the buffer of this message with a string, adds the necessary padding
    */
    public void setBand_Str(String str) {
        int len = Math.min(str.length(), 6);
        for (int i=0; i<len; i++) {
            band_str[i] = (byte) str.charAt(i);
        }

        for (int i=len; i<6; i++) {            // padding for the rest of the buffer
            band_str[i] = 0;
        }
    }

    /**
    * Gets the message, formatted as a string
    */
    public String getBand_Str() {
        StringBuffer buf = new StringBuffer();
        for (int i = 0; i < 6; i++) {
            if (band_str[i] != 0)
                buf.append((char) band_str[i]);
            else
                break;
        }
        return buf.toString();

    }
                             
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_MLRS_RADIO_LINK_INFORMATION - sysid:"+sysid+" compid:"+compid+" tx_frame_rate:"+tx_frame_rate+" rx_frame_rate:"+rx_frame_rate+" tx_ser_data_rate:"+tx_ser_data_rate+" rx_ser_data_rate:"+rx_ser_data_rate+" target_system:"+target_system+" target_component:"+target_component+" type:"+type+" mode:"+mode+" tx_power:"+tx_power+" rx_power:"+rx_power+" mode_str:"+mode_str+" band_str:"+band_str+" tx_receive_sensitivity:"+tx_receive_sensitivity+" rx_receive_sensitivity:"+rx_receive_sensitivity+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_MLRS_RADIO_LINK_INFORMATION";
    }
}
        