/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE MLRS_RADIO_LINK_STATS PACKING
package com.MAVLink.storm32;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Radio link statistics for a MAVLink RC receiver or transmitter and other links. Tx: ground-side device, Rx: vehicle-side device.
        The message is normally emitted in regular time intervals upon each actual or expected reception of an over-the-air data packet on the link.
        A MAVLink RC receiver should emit it shortly after it emits a RADIO_RC_CHANNELS message (if it is emitting that message).
        Per default, rssi values are in MAVLink units: 0 represents weakest signal, 254 represents maximum signal, UINT8_MAX represents unknown.
        The RADIO_LINK_STATS_FLAGS_RSSI_DBM flag is set if the rssi units are negative dBm: 1..254 correspond to -1..-254 dBm, 0 represents no reception, UINT8_MAX represents unknown.
        The target_system field should normally be set to the system id of the system the link is connected to, typically the flight controller.
        The target_component field can normally be set to 0, so that all components of the system can receive the message.
        Note: The frequency fields are extensions to ensure that they are located at the end of the serialized payload and subject to MAVLink's trailing-zero trimming.
      
 */
public class msg_mlrs_radio_link_stats extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_MLRS_RADIO_LINK_STATS = 60045;
    public static final int MAVLINK_MSG_LENGTH = 23;
    private static final long serialVersionUID = MAVLINK_MSG_ID_MLRS_RADIO_LINK_STATS;

    
    /**
     * Radio link statistics flags.
     */
    @Description("Radio link statistics flags.")
    @Units("")
    public int flags;
    
    /**
     * System ID (ID of target system, normally flight controller).
     */
    @Description("System ID (ID of target system, normally flight controller).")
    @Units("")
    public short target_system;
    
    /**
     * Component ID (normally 0 for broadcast).
     */
    @Description("Component ID (normally 0 for broadcast).")
    @Units("")
    public short target_component;
    
    /**
     * Link quality of RC data stream from Tx to Rx. Values: 1..100, 0: no link connection, UINT8_MAX: unknown.
     */
    @Description("Link quality of RC data stream from Tx to Rx. Values: 1..100, 0: no link connection, UINT8_MAX: unknown.")
    @Units("c%")
    public short rx_LQ_rc;
    
    /**
     * Link quality of serial MAVLink data stream from Tx to Rx. Values: 1..100, 0: no link connection, UINT8_MAX: unknown.
     */
    @Description("Link quality of serial MAVLink data stream from Tx to Rx. Values: 1..100, 0: no link connection, UINT8_MAX: unknown.")
    @Units("c%")
    public short rx_LQ_ser;
    
    /**
     * Rssi of antenna 1. 0: no reception, UINT8_MAX: unknown.
     */
    @Description("Rssi of antenna 1. 0: no reception, UINT8_MAX: unknown.")
    @Units("")
    public short rx_rssi1;
    
    /**
     * Noise on antenna 1. Radio link dependent. INT8_MAX: unknown.
     */
    @Description("Noise on antenna 1. Radio link dependent. INT8_MAX: unknown.")
    @Units("")
    public byte rx_snr1;
    
    /**
     * Link quality of serial MAVLink data stream from Rx to Tx. Values: 1..100, 0: no link connection, UINT8_MAX: unknown.
     */
    @Description("Link quality of serial MAVLink data stream from Rx to Tx. Values: 1..100, 0: no link connection, UINT8_MAX: unknown.")
    @Units("c%")
    public short tx_LQ_ser;
    
    /**
     * Rssi of antenna 1. 0: no reception. UINT8_MAX: unknown.
     */
    @Description("Rssi of antenna 1. 0: no reception. UINT8_MAX: unknown.")
    @Units("")
    public short tx_rssi1;
    
    /**
     * Noise on antenna 1. Radio link dependent. INT8_MAX: unknown.
     */
    @Description("Noise on antenna 1. Radio link dependent. INT8_MAX: unknown.")
    @Units("")
    public byte tx_snr1;
    
    /**
     * Rssi of antenna 2. 0: no reception, UINT8_MAX: use rx_rssi1 if it is known else unknown.
     */
    @Description("Rssi of antenna 2. 0: no reception, UINT8_MAX: use rx_rssi1 if it is known else unknown.")
    @Units("")
    public short rx_rssi2;
    
    /**
     * Noise on antenna 2. Radio link dependent. INT8_MAX: use rx_snr1 if it is known else unknown.
     */
    @Description("Noise on antenna 2. Radio link dependent. INT8_MAX: use rx_snr1 if it is known else unknown.")
    @Units("")
    public byte rx_snr2;
    
    /**
     * Rssi of antenna 2. 0: no reception. UINT8_MAX: use tx_rssi1 if it is known else unknown.
     */
    @Description("Rssi of antenna 2. 0: no reception. UINT8_MAX: use tx_rssi1 if it is known else unknown.")
    @Units("")
    public short tx_rssi2;
    
    /**
     * Noise on antenna 2. Radio link dependent. INT8_MAX: use tx_snr1 if it is known else unknown.
     */
    @Description("Noise on antenna 2. Radio link dependent. INT8_MAX: use tx_snr1 if it is known else unknown.")
    @Units("")
    public byte tx_snr2;
    
    /**
     * Frequency on antenna1 in Hz. 0: unknown.
     */
    @Description("Frequency on antenna1 in Hz. 0: unknown.")
    @Units("Hz")
    public float frequency1;
    
    /**
     * Frequency on antenna2 in Hz. 0: unknown.
     */
    @Description("Frequency on antenna2 in Hz. 0: unknown.")
    @Units("Hz")
    public float frequency2;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_MLRS_RADIO_LINK_STATS;

        packet.payload.putUnsignedShort(flags);
        packet.payload.putUnsignedByte(target_system);
        packet.payload.putUnsignedByte(target_component);
        packet.payload.putUnsignedByte(rx_LQ_rc);
        packet.payload.putUnsignedByte(rx_LQ_ser);
        packet.payload.putUnsignedByte(rx_rssi1);
        packet.payload.putByte(rx_snr1);
        packet.payload.putUnsignedByte(tx_LQ_ser);
        packet.payload.putUnsignedByte(tx_rssi1);
        packet.payload.putByte(tx_snr1);
        packet.payload.putUnsignedByte(rx_rssi2);
        packet.payload.putByte(rx_snr2);
        packet.payload.putUnsignedByte(tx_rssi2);
        packet.payload.putByte(tx_snr2);
        
        if (isMavlink2) {
             packet.payload.putFloat(frequency1);
             packet.payload.putFloat(frequency2);
            
        }
        return packet;
    }

    /**
     * Decode a mlrs_radio_link_stats message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.flags = payload.getUnsignedShort();
        this.target_system = payload.getUnsignedByte();
        this.target_component = payload.getUnsignedByte();
        this.rx_LQ_rc = payload.getUnsignedByte();
        this.rx_LQ_ser = payload.getUnsignedByte();
        this.rx_rssi1 = payload.getUnsignedByte();
        this.rx_snr1 = payload.getByte();
        this.tx_LQ_ser = payload.getUnsignedByte();
        this.tx_rssi1 = payload.getUnsignedByte();
        this.tx_snr1 = payload.getByte();
        this.rx_rssi2 = payload.getUnsignedByte();
        this.rx_snr2 = payload.getByte();
        this.tx_rssi2 = payload.getUnsignedByte();
        this.tx_snr2 = payload.getByte();
        
        if (isMavlink2) {
             this.frequency1 = payload.getFloat();
             this.frequency2 = payload.getFloat();
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_mlrs_radio_link_stats() {
        this.msgid = MAVLINK_MSG_ID_MLRS_RADIO_LINK_STATS;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_mlrs_radio_link_stats( int flags, short target_system, short target_component, short rx_LQ_rc, short rx_LQ_ser, short rx_rssi1, byte rx_snr1, short tx_LQ_ser, short tx_rssi1, byte tx_snr1, short rx_rssi2, byte rx_snr2, short tx_rssi2, byte tx_snr2, float frequency1, float frequency2) {
        this.msgid = MAVLINK_MSG_ID_MLRS_RADIO_LINK_STATS;

        this.flags = flags;
        this.target_system = target_system;
        this.target_component = target_component;
        this.rx_LQ_rc = rx_LQ_rc;
        this.rx_LQ_ser = rx_LQ_ser;
        this.rx_rssi1 = rx_rssi1;
        this.rx_snr1 = rx_snr1;
        this.tx_LQ_ser = tx_LQ_ser;
        this.tx_rssi1 = tx_rssi1;
        this.tx_snr1 = tx_snr1;
        this.rx_rssi2 = rx_rssi2;
        this.rx_snr2 = rx_snr2;
        this.tx_rssi2 = tx_rssi2;
        this.tx_snr2 = tx_snr2;
        this.frequency1 = frequency1;
        this.frequency2 = frequency2;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_mlrs_radio_link_stats( int flags, short target_system, short target_component, short rx_LQ_rc, short rx_LQ_ser, short rx_rssi1, byte rx_snr1, short tx_LQ_ser, short tx_rssi1, byte tx_snr1, short rx_rssi2, byte rx_snr2, short tx_rssi2, byte tx_snr2, float frequency1, float frequency2, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_MLRS_RADIO_LINK_STATS;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.flags = flags;
        this.target_system = target_system;
        this.target_component = target_component;
        this.rx_LQ_rc = rx_LQ_rc;
        this.rx_LQ_ser = rx_LQ_ser;
        this.rx_rssi1 = rx_rssi1;
        this.rx_snr1 = rx_snr1;
        this.tx_LQ_ser = tx_LQ_ser;
        this.tx_rssi1 = tx_rssi1;
        this.tx_snr1 = tx_snr1;
        this.rx_rssi2 = rx_rssi2;
        this.rx_snr2 = rx_snr2;
        this.tx_rssi2 = tx_rssi2;
        this.tx_snr2 = tx_snr2;
        this.frequency1 = frequency1;
        this.frequency2 = frequency2;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_mlrs_radio_link_stats(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_MLRS_RADIO_LINK_STATS;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                                    
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_MLRS_RADIO_LINK_STATS - sysid:"+sysid+" compid:"+compid+" flags:"+flags+" target_system:"+target_system+" target_component:"+target_component+" rx_LQ_rc:"+rx_LQ_rc+" rx_LQ_ser:"+rx_LQ_ser+" rx_rssi1:"+rx_rssi1+" rx_snr1:"+rx_snr1+" tx_LQ_ser:"+tx_LQ_ser+" tx_rssi1:"+tx_rssi1+" tx_snr1:"+tx_snr1+" rx_rssi2:"+rx_rssi2+" rx_snr2:"+rx_snr2+" tx_rssi2:"+tx_rssi2+" tx_snr2:"+tx_snr2+" frequency1:"+frequency1+" frequency2:"+frequency2+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_MLRS_RADIO_LINK_STATS";
    }
}
        