/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SENS_POWER PACKING
package com.MAVLink.ASLUAV;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Voltage and current sensor data
 */
public class msg_sens_power extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_SENS_POWER = 8002;
    public static final int MAVLINK_MSG_LENGTH = 16;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SENS_POWER;

    
    /**
     *  Power board voltage sensor reading
     */
    @Description(" Power board voltage sensor reading")
    @Units("V")
    public float adc121_vspb_volt;
    
    /**
     *  Power board current sensor reading
     */
    @Description(" Power board current sensor reading")
    @Units("A")
    public float adc121_cspb_amp;
    
    /**
     *  Board current sensor 1 reading
     */
    @Description(" Board current sensor 1 reading")
    @Units("A")
    public float adc121_cs1_amp;
    
    /**
     *  Board current sensor 2 reading
     */
    @Description(" Board current sensor 2 reading")
    @Units("A")
    public float adc121_cs2_amp;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_SENS_POWER;

        packet.payload.putFloat(adc121_vspb_volt);
        packet.payload.putFloat(adc121_cspb_amp);
        packet.payload.putFloat(adc121_cs1_amp);
        packet.payload.putFloat(adc121_cs2_amp);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a sens_power message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.adc121_vspb_volt = payload.getFloat();
        this.adc121_cspb_amp = payload.getFloat();
        this.adc121_cs1_amp = payload.getFloat();
        this.adc121_cs2_amp = payload.getFloat();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_sens_power() {
        this.msgid = MAVLINK_MSG_ID_SENS_POWER;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_sens_power( float adc121_vspb_volt, float adc121_cspb_amp, float adc121_cs1_amp, float adc121_cs2_amp) {
        this.msgid = MAVLINK_MSG_ID_SENS_POWER;

        this.adc121_vspb_volt = adc121_vspb_volt;
        this.adc121_cspb_amp = adc121_cspb_amp;
        this.adc121_cs1_amp = adc121_cs1_amp;
        this.adc121_cs2_amp = adc121_cs2_amp;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_sens_power( float adc121_vspb_volt, float adc121_cspb_amp, float adc121_cs1_amp, float adc121_cs2_amp, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_SENS_POWER;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.adc121_vspb_volt = adc121_vspb_volt;
        this.adc121_cspb_amp = adc121_cspb_amp;
        this.adc121_cs1_amp = adc121_cs1_amp;
        this.adc121_cs2_amp = adc121_cs2_amp;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_sens_power(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_SENS_POWER;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

            
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_SENS_POWER - sysid:"+sysid+" compid:"+compid+" adc121_vspb_volt:"+adc121_vspb_volt+" adc121_cspb_amp:"+adc121_cspb_amp+" adc121_cs1_amp:"+adc121_cs1_amp+" adc121_cs2_amp:"+adc121_cs2_amp+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_SENS_POWER";
    }
}
        