/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE AHRS2 PACKING
package com.mavlink.ardupilotmega;
import com.mavlink.MAVLinkPacket;
import com.mavlink.messages.MAVLinkMessage;
import com.mavlink.messages.MAVLinkPayload;

import org.json.JSONException;
import org.json.JSONObject;

        
/**
 * Status of secondary AHRS filter if available.
 */
public class msg_ahrs2 extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_AHRS2 = 178;
    public static final int MAVLINK_MSG_LENGTH = 24;
    private static final long serialVersionUID = MAVLINK_MSG_ID_AHRS2;

      
    /**
     * Roll angle.
     */
    public float roll;
      
    /**
     * Pitch angle.
     */
    public float pitch;
      
    /**
     * Yaw angle.
     */
    public float yaw;
      
    /**
     * Altitude (MSL).
     */
    public float altitude;
      
    /**
     * Latitude.
     */
    public int lat;
      
    /**
     * Longitude.
     */
    public int lng;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_AHRS2;
        
        packet.payload.putFloat(roll);
        packet.payload.putFloat(pitch);
        packet.payload.putFloat(yaw);
        packet.payload.putFloat(altitude);
        packet.payload.putInt(lat);
        packet.payload.putInt(lng);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a ahrs2 message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.roll = payload.getFloat();
        this.pitch = payload.getFloat();
        this.yaw = payload.getFloat();
        this.altitude = payload.getFloat();
        this.lat = payload.getInt();
        this.lng = payload.getInt();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_ahrs2() {
        this.msgid = MAVLINK_MSG_ID_AHRS2;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_ahrs2( float roll, float pitch, float yaw, float altitude, int lat, int lng) {
        this.msgid = MAVLINK_MSG_ID_AHRS2;

        this.roll = roll;
        this.pitch = pitch;
        this.yaw = yaw;
        this.altitude = altitude;
        this.lat = lat;
        this.lng = lng;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_ahrs2( float roll, float pitch, float yaw, float altitude, int lat, int lng, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_AHRS2;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.roll = roll;
        this.pitch = pitch;
        this.yaw = yaw;
        this.altitude = altitude;
        this.lat = lat;
        this.lng = lng;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_ahrs2(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_AHRS2;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from JSON Object
     */
    public msg_ahrs2(JSONObject jo) {
        this.msgid = MAVLINK_MSG_ID_AHRS2;

        readJSONheader(jo);
        
        this.roll = (float)jo.optDouble("roll",0);
        this.pitch = (float)jo.optDouble("pitch",0);
        this.yaw = (float)jo.optDouble("yaw",0);
        this.altitude = (float)jo.optDouble("altitude",0);
        this.lat = jo.optInt("lat",0);
        this.lng = jo.optInt("lng",0);
        
        
    }
    
    /**
     * Convert this class to a JSON Object
     */
    @Override
    public JSONObject toJSON() throws JSONException {
        final JSONObject jo = getJSONheader();
        
        jo.put("roll", (double)roll);
        jo.put("pitch", (double)pitch);
        jo.put("yaw", (double)yaw);
        jo.put("altitude", (double)altitude);
        jo.put("lat", lat);
        jo.put("lng", lng);
        
        
        return jo;
    }

                
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_AHRS2 - sysid:"+sysid+" compid:"+compid+" roll:"+roll+" pitch:"+pitch+" yaw:"+yaw+" altitude:"+altitude+" lat:"+lat+" lng:"+lng+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_AHRS2";
    }
}
        