/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE NAMED_VALUE_STRING PACKING
package com.MAVLink.ardupilotmega;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Send a key-value pair as string. The use of this message is discouraged for normal packets, but a quite efficient way for testing new messages and getting experimental debug output.
 */
public class msg_named_value_string extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_NAMED_VALUE_STRING = 11060;
    public static final int MAVLINK_MSG_LENGTH = 78;
    private static final long serialVersionUID = MAVLINK_MSG_ID_NAMED_VALUE_STRING;

    
    /**
     * Timestamp (time since system boot).
     */
    @Description("Timestamp (time since system boot).")
    @Units("ms")
    public long time_boot_ms;
    
    /**
     * Name of the debug variable
     */
    @Description("Name of the debug variable")
    @Units("")
    public byte name[] = new byte[10];
    
    /**
     * Value of the debug variable
     */
    @Description("Value of the debug variable")
    @Units("")
    public byte value[] = new byte[64];
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_NAMED_VALUE_STRING;

        packet.payload.putUnsignedInt(time_boot_ms);
        
        for (int i = 0; i < name.length; i++) {
            packet.payload.putByte(name[i]);
        }
                    
        
        for (int i = 0; i < value.length; i++) {
            packet.payload.putByte(value[i]);
        }
                    
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a named_value_string message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.time_boot_ms = payload.getUnsignedInt();
        
        for (int i = 0; i < this.name.length; i++) {
            this.name[i] = payload.getByte();
        }
                
        
        for (int i = 0; i < this.value.length; i++) {
            this.value[i] = payload.getByte();
        }
                
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_named_value_string() {
        this.msgid = MAVLINK_MSG_ID_NAMED_VALUE_STRING;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_named_value_string( long time_boot_ms, byte[] name, byte[] value) {
        this.msgid = MAVLINK_MSG_ID_NAMED_VALUE_STRING;

        this.time_boot_ms = time_boot_ms;
        this.name = name;
        this.value = value;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_named_value_string( long time_boot_ms, byte[] name, byte[] value, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_NAMED_VALUE_STRING;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.time_boot_ms = time_boot_ms;
        this.name = name;
        this.value = value;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_named_value_string(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_NAMED_VALUE_STRING;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

       
    /**
    * Sets the buffer of this message with a string, adds the necessary padding
    */
    public void setName(String str) {
        int len = Math.min(str.length(), 10);
        for (int i=0; i<len; i++) {
            name[i] = (byte) str.charAt(i);
        }

        for (int i=len; i<10; i++) {            // padding for the rest of the buffer
            name[i] = 0;
        }
    }

    /**
    * Gets the message, formatted as a string
    */
    public String getName() {
        StringBuffer buf = new StringBuffer();
        for (int i = 0; i < 10; i++) {
            if (name[i] != 0)
                buf.append((char) name[i]);
            else
                break;
        }
        return buf.toString();

    }
                          
    /**
    * Sets the buffer of this message with a string, adds the necessary padding
    */
    public void setValue(String str) {
        int len = Math.min(str.length(), 64);
        for (int i=0; i<len; i++) {
            value[i] = (byte) str.charAt(i);
        }

        for (int i=len; i<64; i++) {            // padding for the rest of the buffer
            value[i] = 0;
        }
    }

    /**
    * Gets the message, formatted as a string
    */
    public String getValue() {
        StringBuffer buf = new StringBuffer();
        for (int i = 0; i < 64; i++) {
            if (value[i] != 0)
                buf.append((char) value[i]);
            else
                break;
        }
        return buf.toString();

    }
                         
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_NAMED_VALUE_STRING - sysid:"+sysid+" compid:"+compid+" time_boot_ms:"+time_boot_ms+" name:"+name+" value:"+value+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_NAMED_VALUE_STRING";
    }
}
        