/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE AIRSPEED_AUTOCAL PACKING
package com.mavlink.ardupilotmega;
import com.mavlink.MAVLinkPacket;
import com.mavlink.messages.MAVLinkMessage;
import com.mavlink.messages.MAVLinkPayload;

import org.json.JSONException;
import org.json.JSONObject;

        
/**
 * Airspeed auto-calibration.
 */
public class msg_airspeed_autocal extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_AIRSPEED_AUTOCAL = 174;
    public static final int MAVLINK_MSG_LENGTH = 48;
    private static final long serialVersionUID = MAVLINK_MSG_ID_AIRSPEED_AUTOCAL;

      
    /**
     * GPS velocity north.
     */
    public float vx;
      
    /**
     * GPS velocity east.
     */
    public float vy;
      
    /**
     * GPS velocity down.
     */
    public float vz;
      
    /**
     * Differential pressure.
     */
    public float diff_pressure;
      
    /**
     * Estimated to true airspeed ratio.
     */
    public float EAS2TAS;
      
    /**
     * Airspeed ratio.
     */
    public float ratio;
      
    /**
     * EKF state x.
     */
    public float state_x;
      
    /**
     * EKF state y.
     */
    public float state_y;
      
    /**
     * EKF state z.
     */
    public float state_z;
      
    /**
     * EKF Pax.
     */
    public float Pax;
      
    /**
     * EKF Pby.
     */
    public float Pby;
      
    /**
     * EKF Pcz.
     */
    public float Pcz;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_AIRSPEED_AUTOCAL;
        
        packet.payload.putFloat(vx);
        packet.payload.putFloat(vy);
        packet.payload.putFloat(vz);
        packet.payload.putFloat(diff_pressure);
        packet.payload.putFloat(EAS2TAS);
        packet.payload.putFloat(ratio);
        packet.payload.putFloat(state_x);
        packet.payload.putFloat(state_y);
        packet.payload.putFloat(state_z);
        packet.payload.putFloat(Pax);
        packet.payload.putFloat(Pby);
        packet.payload.putFloat(Pcz);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a airspeed_autocal message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.vx = payload.getFloat();
        this.vy = payload.getFloat();
        this.vz = payload.getFloat();
        this.diff_pressure = payload.getFloat();
        this.EAS2TAS = payload.getFloat();
        this.ratio = payload.getFloat();
        this.state_x = payload.getFloat();
        this.state_y = payload.getFloat();
        this.state_z = payload.getFloat();
        this.Pax = payload.getFloat();
        this.Pby = payload.getFloat();
        this.Pcz = payload.getFloat();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_airspeed_autocal() {
        this.msgid = MAVLINK_MSG_ID_AIRSPEED_AUTOCAL;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_airspeed_autocal( float vx, float vy, float vz, float diff_pressure, float EAS2TAS, float ratio, float state_x, float state_y, float state_z, float Pax, float Pby, float Pcz) {
        this.msgid = MAVLINK_MSG_ID_AIRSPEED_AUTOCAL;

        this.vx = vx;
        this.vy = vy;
        this.vz = vz;
        this.diff_pressure = diff_pressure;
        this.EAS2TAS = EAS2TAS;
        this.ratio = ratio;
        this.state_x = state_x;
        this.state_y = state_y;
        this.state_z = state_z;
        this.Pax = Pax;
        this.Pby = Pby;
        this.Pcz = Pcz;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_airspeed_autocal( float vx, float vy, float vz, float diff_pressure, float EAS2TAS, float ratio, float state_x, float state_y, float state_z, float Pax, float Pby, float Pcz, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_AIRSPEED_AUTOCAL;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.vx = vx;
        this.vy = vy;
        this.vz = vz;
        this.diff_pressure = diff_pressure;
        this.EAS2TAS = EAS2TAS;
        this.ratio = ratio;
        this.state_x = state_x;
        this.state_y = state_y;
        this.state_z = state_z;
        this.Pax = Pax;
        this.Pby = Pby;
        this.Pcz = Pcz;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_airspeed_autocal(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_AIRSPEED_AUTOCAL;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from JSON Object
     */
    public msg_airspeed_autocal(JSONObject jo) {
        this.msgid = MAVLINK_MSG_ID_AIRSPEED_AUTOCAL;

        readJSONheader(jo);
        
        this.vx = (float)jo.optDouble("vx",0);
        this.vy = (float)jo.optDouble("vy",0);
        this.vz = (float)jo.optDouble("vz",0);
        this.diff_pressure = (float)jo.optDouble("diff_pressure",0);
        this.EAS2TAS = (float)jo.optDouble("EAS2TAS",0);
        this.ratio = (float)jo.optDouble("ratio",0);
        this.state_x = (float)jo.optDouble("state_x",0);
        this.state_y = (float)jo.optDouble("state_y",0);
        this.state_z = (float)jo.optDouble("state_z",0);
        this.Pax = (float)jo.optDouble("Pax",0);
        this.Pby = (float)jo.optDouble("Pby",0);
        this.Pcz = (float)jo.optDouble("Pcz",0);
        
        
    }
    
    /**
     * Convert this class to a JSON Object
     */
    @Override
    public JSONObject toJSON() throws JSONException {
        final JSONObject jo = getJSONheader();
        
        jo.put("vx", (double)vx);
        jo.put("vy", (double)vy);
        jo.put("vz", (double)vz);
        jo.put("diff_pressure", (double)diff_pressure);
        jo.put("EAS2TAS", (double)EAS2TAS);
        jo.put("ratio", (double)ratio);
        jo.put("state_x", (double)state_x);
        jo.put("state_y", (double)state_y);
        jo.put("state_z", (double)state_z);
        jo.put("Pax", (double)Pax);
        jo.put("Pby", (double)Pby);
        jo.put("Pcz", (double)Pcz);
        
        
        return jo;
    }

                            
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_AIRSPEED_AUTOCAL - sysid:"+sysid+" compid:"+compid+" vx:"+vx+" vy:"+vy+" vz:"+vz+" diff_pressure:"+diff_pressure+" EAS2TAS:"+EAS2TAS+" ratio:"+ratio+" state_x:"+state_x+" state_y:"+state_y+" state_z:"+state_z+" Pax:"+Pax+" Pby:"+Pby+" Pcz:"+Pcz+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_AIRSPEED_AUTOCAL";
    }
}
        